version: '3.8'

services:
  streamlit:
    build: .
    ports:
      - "8501:8501"
    container_name: streamlit_app
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 5
